spring:
  application.name: ordering
  datasource:
    url: jdbc:h2:file:~/code/kieki/KiekiShop/ordering-db;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
    password: '123'
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: 'true'

kiekishop:
  integrations:
    shipping.provider: "RAPIDEX"
    rapidex.url: "http://localhost:3002"